'use client';

import { MantineProvider } from '@mantine/core';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <MantineProvider withGlobalStyles withNormalizeCSS>
        <body>{children}</body>
      </MantineProvider>
    </html>
  );
}
